// Do not edit this file manually.
// Regenerate this file by running this command in the radio/src/translations folder:
//     m4 simstr.m4 string_list.h > sim_string_list.h
define(`STR', `#define STR_$1 currentLangStrings->STR_$1')
define(`STRARRAY', `#define STR_$1 currentLangStrings->STR_$1')