name: 'Setup WASI SDK'
inputs:
  python-version:
    description: 'Python version'
    default: '3.13'

runs:
  using: "composite"
  steps:

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip' # caching pip dependencies

    - run: python3 -m pip install -r requirements.txt
      shell: bash
