name: 'Setup WASI SDK'
inputs:
  python-version:
    description: 'Python version'
    default: '3.13'

runs:
  using: "composite"
  steps:

    - uses: actions/setup-python@v7
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: pyproject.toml

    - run: python3 -m pip install .
      shell: bash
