---
name: Run tests and package firmware
on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+'
    tags:
      - v*
    paths: &trigger-paths
      - '.github/workflows/build_fw.yml'
      - 'cmake/**'
      - 'radio/**'
      - 'tools/build-gh.sh'
      - '.gitmodules'
      - 'CMakeLists.txt'
  pull_request:
    paths: *trigger-paths

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      github.event_name != 'pull_request' ||
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-fw')
    strategy:
      matrix:
        # each target uses one of the 20 runners available, keep grouped to manage concurrency
        target:
          - el18;nv14 # Flysky
          - nb4p;pa01 # Flysky
          - pl18;pl18ev # Flysky
          - st16 # Flysky
          - x9dp2019;x9e # FrSky
          - x10 # FrSky
          - x12s # FrSky
          - v12 # HelloRadioSky
          - c14 # iFlight
          - t12max;t14 # Jumper
          - t15;t15pro;t15h7 # Jumper
          - t16;t18 # Jumper
          - t20;t20v2 # Jumper
          - t22 # Jumper
          - gx12;mt12 # RadioMaster
          - tx15 # RadioMaster
          - tx16s;tx16smk3 # RadioMaster
          - h17 # Senduwing
    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Test ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          CMAKE_BUILD_PARALLEL_LEVEL: 4
        run: |
          echo "Running commit tests"
          ./tools/commit-tests.sh

  build:
    name: Run builds
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-fw')
    strategy:
      matrix:
        # each target uses one of the 20 runners available, keep grouped to manage concurrency
        target:
          - f16 # Fatfish
          - el18;nv14 # Flysky
          - nb4p;pa01;st16 # Flysky
          - pl18;pl18ev;pl18u # Flysky
          - x10;x10express;x12s # FrSky
          - x7access;x9dp2019;x9e # FrSky
          - v12;v14 # HelloRadioSky
          - v14lcd;v16 # HelloRadioSky
          - c14;commando8 # iFlight
          - bumblebee;t12max;t14 # Jumper
          - t15;t15h7;t15pro;t16 # Jumper
          - t18;t20;t20v2 # Jumper
          - t22;tpros;tprov2 # Jumper
          - boxer;gx12;gx15 # RadioMaster
          - mt12;pocket;tx12mk2 # RadioMaster
          - tx15;tx16s;tx16smk3 # RadioMaster
          - zorro # RadioMaster
          - h17 # Senduwing
    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          CMAKE_BUILD_PARALLEL_LEVEL: 4
        run: |
          echo "Running firmware build"
          ./tools/build-gh.sh

      - name: Upload ${{ matrix.target }}
        uses: actions/upload-artifact@v7
        with:
          name: firmware-${{ matrix.target }}
          path: |
            fw.json
            LICENSE
            *.bin
            *.uf2
          retention-days: 15
          if-no-files-found: error

  package:
    name: Package firmwares
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Compose release filename
        run: echo "artifact_name=edgetx-firmware-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Merge firmware artifact packages
        uses: actions/upload-artifact/merge@v7
        with:
          name: "${{ env.artifact_name }}"
          pattern: firmware-*
          delete-merged: true
          retention-days: 15
