name: Companion

on:
  push:
    branches:
      - 'main'
    tags:
      - v*
    paths:
      - '.github/workflows/companion.yml'
      - 'companion/**'
      - 'tools/build-companion.sh'

  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/companion.yml'
      - 'companion/**'
      - 'tools/build-companion.sh'

  workflow_dispatch:

jobs:
  build-modules:
    name: WASM Modules
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/edgetx/edgetx-wasi:pr-37
      volumes:
        - ${{ github.workspace }}:/src

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build modules
        shell: bash
        env:
          CMAKE_BUILD_TYPE: 'Release'
        run: |
          mkdir output && \
          tools/build-wasm-modules.sh "$(pwd)" "$(pwd)/output/"

      - name: Compose artifact name
        run: echo "artifact_name=edgetx-modules-${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.artifact_name }}"
          path:  ${{github.workspace}}/output
          retention-days: 15

  build-linux:
    name: Linux Companion
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup and Build
        uses: ./.github/actions/build_companion
        with:
          os: 'linux'

  build-macos:
    name: macOS Companion
    runs-on: macos-14

    env:
      CMAKE_OSX_ARCHITECTURES: 'x86_64'
      CMAKE_OSX_DEPLOYMENT_TARGET: '10.15'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup and Build
        uses: ./.github/actions/build_companion
        with:
          os: 'macos'
          qt-arch: 'clang_64'

  build-win64:
    name: Windows Companion
    runs-on: windows-2022

    env:
      CMAKE_GENERATOR: 'Ninja'
      CXX: 'clang++'
      CC: 'clang'

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup and Build
        uses: ./.github/actions/build_companion
        with:
          os: 'win64'
          qt-arch: 'win64_msvc2022_64'
