name: Companion

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+'
    tags:
      - v*
    paths: &trigger-paths
      - '.github/workflows/companion.yml'
      - '.github/workflows/linux_cpn.yml'
      - '.github/workflows/macosx_cpn.yml'
      - '.github/workflows/win_cpn-64.yml'
      - 'companion/**'
      - 'tools/build-companion.sh'

  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+'
    paths: *trigger-paths

  workflow_dispatch:
    inputs:
      target:
        description: 'Build target'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - linux
          - macos
          - windows

jobs:
  build-linux:
    name: Linux
    if: inputs.target == 'all' || inputs.target == 'linux' || inputs.target == ''
    uses: ./.github/workflows/linux_cpn.yml

  build-macos:
    name: macOS
    if: inputs.target == 'all' || inputs.target == 'macos' || inputs.target == ''
    uses: ./.github/workflows/macosx_cpn.yml

  build-win64:
    name: Windows
    if: inputs.target == 'all' || inputs.target == 'windows' || inputs.target == ''
    uses: ./.github/workflows/win_cpn-64.yml
