name: Linux Companion

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-cpn-linux')
    container:
      image: ghcr.io/edgetx/edgetx-dev:2.12
      volumes:
        - ${{ github.workspace }}:/src

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup and Build
        uses: ./.github/actions/build_companion
        with:
          os: 'linux'
