name: Windows Companion 64-bit

on:
  workflow_call:
  workflow_dispatch:

env:
  CMAKE_GENERATOR: "Ninja"
  CXX: "clang++"
  CC: "clang"

jobs:
  build:
    runs-on: windows-2022
    if: |
      github.event_name != 'pull_request' ||
      !contains(github.event.pull_request.labels.*.name, 'ci: skip-cpn-win')
    defaults:
      run:
        shell: bash

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip clang jinja2 lz4 pillow

      - name: Setup and Build
        uses: ./.github/actions/build_companion
        with:
          os: 'win64'
          qt-arch: 'win64_msvc2022_64'
          # Python 3.12 above already provisioned the codegen packages
          setup-python: 'false'
